FROM --platform=linux/arm/v7 python:3.10-bullseye

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    build-essential \
    file \
    git \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
